feat: added Lighthouse CI to github actions

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -25,9 +25,31 @@ jobs:
 
       - name: Linter
         run: npm run lint
-      
-      - name: Build
-        run: npm run build
 
       - name: Run tests
         run: npm test
+
+      - name: Build
+        run: npm run build
+  
+
+  lighthouse-ci:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20' 
+          cache: 'npm'
+        
+      - name: Install packages
+        run: npm ci
+
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+
