test: testing modified lighthouse config

diff --git a/.github/workflows/lighthouse.yaml b/.github/workflows/lighthouse.yaml
--- a/.github/workflows/lighthouse.yaml
+++ b/.github/workflows/lighthouse.yaml
@@ -35,13 +35,13 @@ jobs:
       #     LHCI_GITHUB_APP_TOKEN: $
           
       - name: Run Lighthouse CI
-        run: npx @lhci/cli autorun --config=./lighthouserc.json || echo "LHCI failed!"
+        run: npx @lhci/cli autorun --config=./lighthouserc.js || echo "LHCI failed!"
 
       - name: Upload Lighthouse reports
         uses: actions/upload-artifact@v4
         with:
             name: lighthouse-report
-            path: lhci-report/
+            path: .lighthouseci/reports
 
       - name: Comment (or update) PR with Lighthouse summary
         if: github.event.pull_request
